#!/bin/bash

start(){
  ./EventNotifier &
}

stop(){
  killall EventNotifier
}


case $1 in
start)
  echo "Starting EventNotifier"
  start
  ;;
stop)
  echo "Stopping EventNotifier"
  stop
  ;;
reload|restart)
  echo "Restarting EventNotifier"
  stop
  sleep 1
  start
  ;;
*)
  echo "Usage: $0 {start|stop|restart|reload}"
  exit 1
esac
exit 0
