#!/bin/bash

start(){
  ./IpChangeNotifier &
}

stop(){
  killall IpChangeNotifier
}


case $1 in
start)
  echo "Starting IpChangeNotifier"
  start
  ;;
stop)
  echo "Stopping IpChangeNotifier"
  stop
  ;;
reload|restart)
  echo "Restarting IpChangeNotifier"
  stop
  sleep 1
  start
  ;;
*)
  echo "Usage: $0 {start|stop|restart|reload}"
  exit 1
esac
exit 0
