#!/bin/bash

# -- IpChangeNotifier --
# Author: Carlos Carrizosa
# Brief: This script sends an email every time the external ip changes
#        or detects connectivity problems.

# -- Configuration section -- 

configFile=./ICNConfig.cfg

if [ ! -e "$configFile" ]
then
  echo "Failed to load configuration File: $configFile" && exit 1
fi

. $configFile

if [ -z "$email" ]
then
  echo "Error: Missing email in configuration file" && exit 1
fi

[ -z "$sleepTime" ] && sleepTime=15
[ -z "$tempFile" ] && tempFile=/tmp/IpChangeNotifierMail.tmp


# -- Code -- #

# Initialize local variable
downTime=''

# Command to get IP
ipCommand='wget -O - -q http://ipecho.net/plain'

# Get external IP
lastIP=`$ipCommand`

while [ true ]
do
  # Get current IP
  currentIP=`$ipCommand`
   
  # Check if computer has external connection and ipCommand works fine
  if [ $currentIP  ]
  then

    # Check if external IP has changed
    if [ "$lastIP" != "$currentIP" ]
    then
      # if has changed, generate the mail body and send it
      echo "IP Changed" > $tempFile
      echo "Last IP: $lastIP" >> $tempFile
      echo "Current IP: $currentIP" >> $tempFile
      date -u >> $tempFile
    
      cat $tempFile | mail -s "[IpChangeNotifier] IP Changed" $email

      lastIP=$currentIP
    fi

    # Also check if there was connection errors
    if [ -n "$downTime" ]
    then
      echo "Connection Problem detected" > $tempFile
      echo "Connection was lost at $downTime" >> $tempFile
      echo "Connection recovered at "`date -u` >> $tempFile

      cat $tempFile | mail -s "[IpChangeNotifier] Connection Problem!" $email

      downTime=''
    fi

  else
    # ipCommand is not working. Perhaps connection is down?
    if [ -z "$downTime" ]
    then
      downTime=`date -u`
    fi
  fi
  sleep $sleepTime"m"
done
