#!/bin/bash

# -- IP Changes notifier --
# Author: Carlos Carrizosa
# Last Modified: 24-07-2012
# Brief: This script sends an email every time the external ip changes.

# Config
email=your@mail.com
sleepTime=900
tempFile=/tmp/eventNotifier.log

# Code

downTime=''

# Command to get IP
ipCommand='wget -O - -q http://automation.whatismyip.com/n09230945.asp'

# Get external IP
lastIP=`$ipCommand`

while [ -e  ]
do
  # Get current IP
  currentIP=`$ipCommand`
   
  # Check if computer has external connection and ipCommand works fine
  if [ $currentIP  ]
  then

    # Check if external IP has changed
    if [ "$lastIP" != "$currentIP" ]
    then
      # if has changed, generate the mail body and send it
      echo "IP Changed" > $tempFile
      echo "Last IP: $lastIP" >> $tempFile
      echo "Current IP: $currentIP" >> $tempFile
      date -u >> $tempFile
    
      cat $tempFile | mail -s "[EventNotifier] IP Changed" $email

      lastIP=$currentIP
    fi

    # Also check if there was connection errors
    if [ -n "$downTime" ]
    then
      echo "Connection Problem detected" > $tempFile
      echo "Connection was lost at $downTime" >> $tempFile
      echo "Connection recovered at "`date -u` >> $tempFile

      cat $tempFile | mail -s "[EventNotifier] Connection Problem!" $email

      downTime=''
    fi

  else
    # ipCommand is not working. Perhaps connection is down?
    if [ -z "$downTime" ]
    then
      downTime=`date -u`
    fi
  fi
  sleep $sleepTime
done
